Feature Flag for ENS
decentraland/builder pull request #1145
Opened 2020-10-27 14:19 UTC by malaniz

Feature Flag for ENS

If REACT_APP_FF_ENS exist then will be turned on, if not defined will be turned OFF.

2020-10-27 23:39 UTC, cazala requested changes
i think we should also add this env var to the `now.json` file. Also maybe there are other missing env vars from the ens branch that we should add there so the feature works on the vercel previews

2020-10-28 15:11 UTC, cazala commented on src/components/LandDetailPage/LandDetailPage.tsx
> +import { env } from 'decentraland-commons'
nip tick: cam we move this import to the top? we usually have the modules on top and the relative imports below

2020-10-28 15:11 UTC, cazala approved these changes

2020-10-28 17:42 UTC, nicosantangelo approved these changes
LGTM super minor comment. I'll approve anyways

2020-10-28 17:42 UTC, nicosantangelo commented on src/components/LandDetailPage/LandDetailPage.tsx
> +                          {FF_ENS ? (
Sorry I saw this one second, but could we change it to look the same as the one juanca did? here https://github.com/decentraland/builder/pull/1151/files#diff-e6f76a45490df7734399812bad8e19dda9c880883a47f3101bf25025124d65afR20

it's super minor, but for consistency sake

2020-10-28 17:42 UTC, nicosantangelo commented on src/routing/Routes.tsx
> +            { FF_ENS && <Route exact path={locations.landEns()} component={LandEnsPage} /> }
Same comment as above

2020-10-29 16:06 UTC, nicosantangelo approved these changes
🔥

2020-10-29 16:06 UTC, merged