feat: re assign ens
decentraland/builder pull request #1180
Opened 2020-11-12 23:19 UTC by nicosantangelo

Closes #1141

2020-11-16 23:17 UTC, cazala commented
A few thingys:

1) The navigation in the `/set-name` page is showing the tabs and not showing the back button, and the map is missing the rounded corners:

<img width="1178" alt="Screen Shot 2020-11-16 at 7 39 50 PM" src="https://user-images.githubusercontent.com/2781777/99319322-18936000-2848-11eb-8f9b-e13086074361.png">

Designs:

<img width="664" alt="Screen Shot 2020-11-16 at 8 14 49 PM" src="https://user-images.githubusercontent.com/2781777/99319508-6a3bea80-2848-11eb-8e70-4b336eef4b4f.png">

2) When I click on the Wearables tab, the app blows up, and the router complains with: 

```
Warning: <Route> elements should not change from uncontrolled to controlled (or vice versa). You initially used no "location" prop and then provided one on a subsequent render.
```

Seems like a rebase issue?

Other than these minor issues the functionality of the feature is working as expected 👍

2020-11-17 07:01 UTC, malaniz requested changes
There is only one detail that I found. When you want to assign a land that is currently used for that domain it goes to the `SetResolver / SetContent` page with only available "Finish Button".
![img-bUK9Bs_000](https://user-images.githubusercontent.com/477970/99356786-8744dd80-2889-11eb-9fd0-6f9ed5c1eafc.png)

I think it is a good idea to check and show a message as we made in the /land/<coord>/set-name and disabling the `continue` button.

2020-11-17 17:40 UTC, malaniz approved these changes
LGTM!

2020-11-17 18:06 UTC, cazala approved these changes

2020-11-17 20:31 UTC, merged