Feat/global minters
decentraland/builder pull request #1442
Opened 2021-06-12 00:02 UTC by nicosantangelo

Closes #1421 
Closes #1388

2021-06-14 20:06 UTC, nachomazzara commented
Feedback from usage:

- As a minter I should only see `mint`. I can't edit the item files in the editor or the price.

<img width="1118" alt="Screen Shot 2021-06-14 at 16 58 47" src="https://user-images.githubusercontent.com/7549152/121951875-de346780-cd31-11eb-84d0-fd859b245ebe.png">

- When the collection is on sale and I want to remove a winter, it removes also the store as a winter.

- Weird behavior when I tried to remove and add another collaborator within the same txs

https://user-images.githubusercontent.com/7549152/121952626-e17c2300-cd32-11eb-9c05-4ecbfca8fb01.mov

2021-06-15 01:38 UTC, nachomazzara requested changes
Thanks nico! just a few comments.

Also, I'm still seeing the collection with the option as `Open in editor` when I'm only a minter.

2021-06-15 01:38 UTC, nachomazzara commented on src/components/Modals/ManageCollectionRoleModal/ManageCollectionRoleModal.tsx
> +    const originalRoles = metadata.roles
If the collection is on sale we are "removing" the store address because it is not at `this.state.roles` but at `originalRoles`, right?

2021-06-15 01:38 UTC, nachomazzara commented on src/components/Modals/ManageCollectionRoleModal/ManageCollectionRoleModal.tsx
> +    accessList.push(...setOnSale(collection, wallet, isOnSale(collection, wallet)))
Following the comment above. We are "adding" again the store here if it should be turned on, and therefore the transaction has a _turn off and on_ of the store. `[..., store, store], [...,false, true]`

2021-06-15 01:38 UTC, nachomazzara commented on src/components/Modals/ManageCollectionRoleModal/ManageCollectionRoleModal.tsx
> +    return this.getStartRoles().length !== this.state.roles.filter(role => !!role).length
May are we missing the case when a user removes and adds another address? I guess that comparing against the length is not 100% correct.

2021-06-15 01:38 UTC, nachomazzara commented on src/components/Modals/ManageCollectionRoleModal/ManageCollectionRoleModal.tsx
> +    const originalRoles = metadata.roles
I guess that the same is happening when trying to add collaborators

2021-06-15 01:38 UTC, nachomazzara commented on src/components/Modals/ManageCollectionRoleModal/ManageCollectionRoleModal.tsx
> +    accessList.push(...setOnSale(collection, wallet, isOnSale(collection, wallet)))
Can we omit the store address if we are editing collaborators?

2021-06-15 01:38 UTC, nachomazzara commented on src/modules/translation/languages/en.json
> +    "added_collection_minters": "Added {count} {count, plural, one {minter} other {minterss}} on the collection {name}",
missed for `es`  and `zh`

2021-06-15 01:38 UTC, nachomazzara commented on src/modules/translation/languages/en.json
> +    "minters": "Minters",
Missed for `es` and `zh`

2021-06-15 01:38 UTC, nachomazzara commented on src/modules/translation/languages/es.json
> +      "subtitle": "Enter the ETH address you want to allow for minting your items",
too much spanglish

2021-06-15 16:20 UTC, nicosantangelo commented
> Also, I'm still seeing the collection with the option as Open in editor when I'm only a minter.

oh, I did that on purpose because the collection will be published and thus, can be seen by everyone, right? @nachomazzara

2021-06-15 16:41 UTC, nicosantangelo commented
# Tests

## Managers

- Try to visit a collection you don't have access to and check it says not found

- Add 1> collaborators
	- Check activity to see if the text is correct
	- Use one of those addresses to check if you can enter and manage the collection

- Remove 1> collaborators
	- Check activity to see if the text is correct
	- Use one of those addresses to check if you can no longer enter the collection

## Minters

- Try to visit a collection you don't have access to and check it says not found

- Using a collection on sale and not on sale
	◦ Add 1> minters
		- Check activity to see if the text is correct
		- Use one of those addresses to check if you can enter and ONLY mint the collection items

	◦ Remove 1> minters
		- Check activity to see if the text is correct
		- Use one of those addresses to check if you can no longer enter the collection

## Both

- For both collaborators and minters, play around with the modal and check that the CONFIRM button sets to disabled when the inital state is reached (adding and removing addresses).
	- Play special attention to the Minters section, check with the collection on sale and NOT on sale

2021-06-16 00:20 UTC, nachomazzara commented
More feedback:

- If I remove a collaborator and add another one, I get:
<img width="1127" alt="Screen Shot 2021-06-15 at 21 15 34" src="https://user-images.githubusercontent.com/7549152/122139206-d6062600-ce1e-11eb-8f53-82f5c844888f.png">

- If I remove a minter, I get:  

<img width="1145" alt="Screen Shot 2021-06-15 at 21 13 26" src="https://user-images.githubusercontent.com/7549152/122139191-cc7cbe00-ce1e-11eb-8f6a-7c876cb68b93.png">

- If I add a minter, I get: 

<img width="1138" alt="Screen Shot 2021-06-15 at 21 16 31" src="https://user-images.githubusercontent.com/7549152/122139259-f6ce7b80-ce1e-11eb-9ef3-be3a8a26474c.png">

2021-06-16 16:30 UTC, nachomazzara approved these changes

2021-06-16 16:30 UTC, merged