feat: show grants/revokes on transaction activity
decentraland/builder pull request #1505
Opened 2021-08-11 19:40 UTC by nicosantangelo

![image](https://user-images.githubusercontent.com/692077/129092558-1a17a4b7-0ee8-469a-a38b-aab92477c1ae.png)

Closes #1504

2021-08-18 13:36 UTC, nachomazzara approved these changes

2021-08-18 14:45 UTC, LautaroPetaccio requested changes

2021-08-18 14:45 UTC, LautaroPetaccio commented on src/modules/translation/languages/es.json
> +    "not_approved": "desaprobó",
```suggestion
    "not_approved": "Desaprobaste",
```

2021-08-18 14:45 UTC, LautaroPetaccio commented on src/modules/translation/languages/es.json
> +    "approve_token": "{action} al contrato de {contract} para que opere tokens de {token} por tí.",
```suggestion
    "approve_token": "{action} al contrato {contract} para que opere {token} por tí.",
```

2021-08-18 14:45 UTC, LautaroPetaccio commented on src/modules/translation/languages/es.json
> +    "approve_token": "{action} al contrato de {contract} para que opere tokens de {token} por tí.",
This suggestion comes from:
![Screen Shot 2021-08-18 at 11 33 46](https://user-images.githubusercontent.com/1120791/129919304-d248f40d-fc61-45f9-8fc0-95b866f4d1bd.png)

2021-08-20 14:32 UTC, LautaroPetaccio approved these changes

2021-08-20 14:39 UTC, merged