feat: Upload redirection file via server
decentraland/builder pull request #2264
Opened 2022-08-23 15:32 UTC by fzavalia

2022-08-24 15:00 UTC, LautaroPetaccio requested changes

2022-08-24 15:00 UTC, LautaroPetaccio commented on src/modules/ens/sagas.ts
> +          content: currentContent || ethers.constants.AddressZero,
The `??` might be semantically a bit better than the or:
```suggestion
          content: currentContent ?? ethers.constants.AddressZero,
```

2022-08-24 20:09 UTC, fzavalia commented on src/modules/ens/sagas.ts
> +function handleFetchENSRequest(builderClient: BuilderClient) {
I did that initially, but changed it to this approach because doing that would make the PR really hard to review as everything will show as changed

2022-08-25 21:06 UTC, fzavalia commented on src/modules/ens/sagas.ts
> +function handleFetchENSRequest(builderClient: BuilderClient) {
Move it all inside the root saga

2022-08-29 14:13 UTC, LautaroPetaccio approved these changes

2022-08-29 14:27 UTC, merged