fix: Show single emotes in the emote dropdown button
decentraland/builder pull request #2268
Opened 2022-08-24 16:25 UTC by cyaiox

This PR allows showing single emotes in the play emotes dropdown button.

Emotes in the Items tab:
![image](https://user-images.githubusercontent.com/3170051/186470762-6e2ba1cb-6137-4a6f-9c3d-2a03d2a1845d.png)

Emotes in the Collection tab:
![image](https://user-images.githubusercontent.com/3170051/186470895-e84828f5-d0b1-4b90-9902-044cfc6d4abc.png)

2022-08-24 18:36 UTC, juanmahidalgo requested changes
Testing the request change! Ignore this comment.

2022-08-24 19:12 UTC, juanmahidalgo requested changes
again, just trying to get this notified in Slack, ignore this comment 😂

2022-08-24 19:15 UTC, juanmahidalgo approved these changes

2022-08-24 19:17 UTC, juanmahidalgo reviewed
a comment without approval

2022-08-24 19:41 UTC, juanmahidalgo requested changes
a change request test

2022-08-24 19:58 UTC, juanmahidalgo approved these changes
ok, enough tests, approved for real now 😂  @cyaiox merge when ready

2022-08-25 19:15 UTC, cyaiox commented on src/modules/item/sagas.ts
> +    const ItemModals = ['EditItemURNModal', 'EditPriceAndBeneficiaryModal', 'AddExistingItemModal']
This change is not related to this issue. It closes all opened modals when creating/updating an item.

2022-08-25 19:24 UTC, juanmahidalgo commented on src/components/CollectionProvider/CollectionProvider.tsx
> +        if (!(itemsPage as number[]).includes(nextPage)) {
```suggestion
        if (Array.isArray(itemsPage) && !itemsPage.includes(nextPage)) {
```
:)

2022-08-25 20:54 UTC, merged