feat: create a confirmation modal on mint items from collection
decentraland/builder pull request #2436
Opened 2022-11-18 19:27 UTC by flobarreto

closes #1566

2022-11-18 19:34 UTC, flobarreto commented
<img width="892" alt="image" src="https://user-images.githubusercontent.com/32873485/202787720-48a9f48f-9929-4716-9378-3360b3a564f9.png">

2022-11-21 15:27 UTC, LautaroPetaccio requested changes

2022-11-21 15:27 UTC, LautaroPetaccio commented on src/components/Modals/MintItemsModal/MintItemsModal.tsx
> +                    disabled={isDisabled || !!error}
If I'm not wrong the `!!error` condition shouldn't be here, but in the confirm button, right?

2022-11-21 15:27 UTC, LautaroPetaccio commented on src/modules/translation/languages/en.json
> +    "confirm_title":  "You are about to mint {amount} items, each item will be minted to the given address with the provided amount.",
There's a way to write different cases of plurality differently, for example, if there's one item to be minted, we can write "item" and when there are several, we can write "items":
```suggestion
    "confirm_title":  "You are about to mint {amount} {count, plural, one {item} other {items}}, each item will be minted to the given address with the provided amount.",
```

2022-11-21 15:28 UTC, LautaroPetaccio commented
There seems to be a difference in styling when there are multiple addresses used to mint an item:
<img width="675" alt="Screen Shot 2022-11-21 at 12 12 30" src="https://user-images.githubusercontent.com/1120791/203093490-18baec8c-beea-4fce-8cab-c5fe49ac08d0.png">
<img width="679" alt="Screen Shot 2022-11-21 at 12 12 23" src="https://user-images.githubusercontent.com/1120791/203093503-9cc171ab-fdab-4abc-a149-88393b4135e4.png">
Would you mind checking it as well?

2022-11-22 15:38 UTC, flobarreto commented on src/components/Modals/MintItemsModal/MintItemsModal.tsx
> +              ) : null}
This was the original code not changed for this pr

2022-11-22 15:39 UTC, flobarreto commented on src/components/Modals/MintItemsModal/MintItemsModal.tsx
> +                  }
created a handleView to resuse it on next button

2022-11-22 19:22 UTC, LautaroPetaccio requested changes

2022-11-22 19:22 UTC, LautaroPetaccio commented on src/components/Modals/MintItemsModal/MintItemsModal.tsx
> +    // ! this function goes inside render to retriger rendering of the item dropdown when the selection of items changes
```suggestion
    // ! this function goes inside render to re-trigger the rendering of the item dropdown when the selection of items changes
```

2022-11-22 19:22 UTC, LautaroPetaccio commented on src/components/Modals/MintItemsModal/MintItemsModal.tsx
> +export enum View {
Would you mind moving the `View` enum type to types?

2022-11-22 19:22 UTC, LautaroPetaccio commented on src/modules/translation/languages/es.json
> +    "confirm_title": "Estas por mintear  {count} {count, plural, un {item} other {items}}, cada item va a ser minteado a la dirección indicada con la cantidad seleccionada.",
The `{count, plural, one` is part of the logic to pluralize text:
```suggestion
    "confirm_title": "Estas por mintear {count} {count, plural, one {item} other {items}}, cada item va a ser minteado a la dirección indicada con la cantidad seleccionada.",
```

2022-11-22 19:22 UTC, LautaroPetaccio commented on src/modules/translation/languages/zh.json
> +    "confirm_title": "您將要鑄造 {count} {count, plural, 一 {Asset} other {Assets}} 件物品，每件物品都將以提供的數量鑄造到給定的地址。",
It seems that in Chinese there's no need to use the pluralized form.
If you translate:
```
You are about to mint 1 item, each item will be minted to the given address with the provided amount.
```
and replace 1 to {count}, it should work fine.

2022-11-22 19:22 UTC, LautaroPetaccio commented on src/components/Modals/MintItemsModal/MintItemsModal.tsx
> +      const totalMints = mints.reduce((acc, mint) => {
```suggestion
      const totalMintsPerItem = mints.reduce((acc, mint) => {
```

2022-11-22 19:22 UTC, LautaroPetaccio commented on src/components/Modals/MintItemsModal/MintItemsModal.tsx
> +    const amountItemsValue = Object.values(itemMints).reduce((accumulator, mints) => {
```suggestion
    const totalMints = Object.values(itemMints).reduce((accumulator, mints) => {
```

2022-11-22 19:22 UTC, LautaroPetaccio commented on src/components/Modals/MintItemsModal/MintItemsModal.tsx
> +            <Form>
This comment was not answered, would you mind answering it?

2022-11-22 20:08 UTC, flobarreto commented on src/components/Modals/MintItemsModal/MintItemsModal.css
> +  max-width: 36px;
this does not work, is set as this in other parts inside the project

2022-11-22 20:15 UTC, flobarreto commented on src/components/Modals/MintItemsModal/MintItemsModal.tsx
> +            <Form>
styles looks okay without the form component :)

2022-11-23 13:57 UTC, LautaroPetaccio commented on src/components/Modals/MintItemsModal/MintItemsModal.tsx
> +        ...prevState,
Would you mind removing `...prevState` here?

2022-11-23 14:41 UTC, LautaroPetaccio approved these changes

2022-11-23 14:41 UTC, merged