feat: Update builder homepage screen
decentraland/builder pull request #2437
Opened 2022-11-18 21:51 UTC by cyaiox

This PR renames the current `homepage screen` to `scenes screen` and creates a new homepage overview.

![image](https://user-images.githubusercontent.com/3170051/202809211-f6f21fd3-5fd5-4cf7-a380-186c5a5e07ff.png)

Closes #2345

2022-11-22 13:08 UTC, cyaiox commented on src/components/HomePage/HomePage.tsx
> +  const lastVisitedSection = localStorage.getItem(LOCALSTORAGE_LAST_VISITED_SECTION_KEY)
great idea! I'll be adding it soon 🙌

2022-11-22 16:20 UTC, cyaiox commented on src/components/HomePage/HomePage.tsx
> +        return 'https://docs.decentraland.org/creator/builder/builder-101/#collections'
Hey @juanmahidalgo -- thanks for the feedback! I've just updated the associated links

2022-11-23 19:57 UTC, fzavalia requested changes
Going to collections via overview and clicking the back button on the browser will not take me back to overview. It keeps looping on the collections tab. Can we fix that?

2022-11-23 19:58 UTC, fzavalia commented
> Going to collections via overview and clicking the back button on the browser will not take me back to overview. It keeps looping on the collections tab. Can we fix that?

It happens for all tabs as well

2022-11-23 20:01 UTC, fzavalia commented
> Going to collections via overview and clicking the back button on the browser will not take me back to overview. It keeps looping on the collections tab. Can we fix that?

I think it happens due to the useEffect in the HomePage which redirects back

2022-11-24 17:30 UTC, fzavalia approved these changes

2022-11-24 19:08 UTC, merged